<!DOCTYPE html>
<html lang="RU-ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" id="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>Регистрация</title>
  <base href="">
  <link rel="stylesheet" href="css/app.css">
</head>
<body>
  <?php require_once(ROOT."/template/layout/top.phtml"); ?>
  <?php require_once(ROOT."/template/layout/menu.phtml"); ?>
  <div class="box">
    <div class="rows">
      <div class="columm-12 first">
        <h1 class="text-align">Регистрация</h1>
        <form action="#" method="post" class="registration">
          <label>
            <span>Имя</span>
            <input type="text">
          </label>
          <label>
            <span>Фамилия</span>
            <input type="text">
          </label>
          <label>
            <span>Придумайте логин</span>
            <input type="text">
          </label>
          <label>
            <span>Придумайте пароль</span>
            <input type="text">
          </label>
          <label>
            <span>Повторите, чтобы не ошибиться</span>
            <input type="text">
          </label>
          <input type="submit" value="Зарегистрироваться" class="btn btn--big">
        </form>
      </div>
    </div>
  </div>
  <script data-main="js/app" src="js/require.js"></script>
</body>
</html>