<!DOCTYPE html>
<html lang="RU-ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" id="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>new project lexistudio.ru</title>
  <base href="">
  <link rel="stylesheet" href="css/app.css">
</head>
<body>
  <?php require_once(ROOT."/template/layout/top.phtml"); ?>
  <?php require_once(ROOT."/template/layout/menu.phtml"); ?>

  <script data-main="js/app" src="js/require.js"></script>
</body>
</html>